title: Justin Cho's Website
author: Justin Cho 
email: jcho@isi.edu 
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to Hyundong Justin Cho's personal website! I am a prospective PhD student at USC who is passionate about research in natural language processing. You can find a summary of my research endeavors and a link to my blog post here. 
show_excerpts: true # set to true to show excerpts on the homepage

collections: 
  recreation: 
    output: true
    sort_by: date
  research:
    output: true
    permalink: /:name

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Justin Cho
  tagline: NLP Research Programmer
  affiliations: 
    - name: USC Information Sciences Institute
      link: https://www.isi.edu/
    - name: Computer Science graduate of HKUST
      link: https://www.ust.hk/home 
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: justin-cho


  # generate social links in footer
  social_links:
    twitter: HJCH0
    github:  wise-east
    linkedIn: in/justin-hyundong-cho/
    # rss: 
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md


remote_theme: thelehhman/plainwhite-jekyll
# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
  # - jekyll-paginate
#  - jekyll-feed
